[package]
name = "nadoeda_scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
nadoeda_models = { version = "0.1.0", path = "../nadoeda_models" }

[features]
default = []
test-util = []
