[package]
name = "nadoeda_models"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
chrono-tz = { version = "0.10.4", features = ["case-insensitive", "serde"] }
serde = { version = "1.0.219", features = ["derive"] }
